image: node:12

stages:
  - install
  - lint
  - test
  - deploy

cache:
  paths:
    - node_modules/

install:
  stage: install
  script:
    - yarn install

lint:
  stage: lint
  script:
    - yarn lint:js:pure . --format junit --output-file ./reports/lint.xml
    - yarn lint:md:all
  artifacts:
    reports:
      junit: 'reports/lint.xml'

unit:
  stage: test
  script: |
    JEST_JUNIT_OUTPUT=reports/unit.xml \
    yarn test:ci:common \
    --coverageDirectory ./reports/unit-coverage \
    test/unit
  coverage: '/All\sfiles.*?\s+(\d+.\d+)/'
  artifacts:
    reports:
      junit: 'reports/unit.xml'
    paths:
      - reports/unit-coverage
    expire_in: 18 months

integration:
  stage: test
  script: |
    JEST_JUNIT_OUTPUT=reports/integration.xml \  
    yarn test:ci:common \
    --coverageDirectory ./reports/integration-coverage \
    test/integration
  coverage: '/All\sfiles.*?\s+(\d+.\d+)/'
  artifacts:
    reports:
      junit: 'reports/integration.xml'
    paths:
      - reports/integration-coverage
    expire_in: 18 months

pages:
  stage: deploy
  dependencies:
    - unit
    - integration
  script:
    - mv unit-coverage/ public/
    - mv integration-coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
